server:
  port: 9000
spring:
  application:
    name: cards  # must be the same as prefix of profiles in config repo
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:mem:testdbCards
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  config:
    import: "optional:configserver:http://localhost:8071"  # config server url
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: refresh,bus-refresh