spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 2s

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 1s


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
        access: unrestricted
  info:
    env:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000

server:
  port: 8072

info:
  app:
    name: "gatewayserver"
    description: "FinBank API Gateway Server"
    version: "4.0.0"
logging:
  level:
    com:
      ar2030:
        finbank:
          gatewayserver: DEBUG