server:
  port: 8090
spring:
  application:
    name: loans  # must be the same as prefix of profiles in config repo
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071"  # config server url
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: refresh,bus-refresh