services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-services

  configserver:
    image: "ar2030/configserver:v2"
    container_name: "configserver-ms"
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
    extends:
      file: common-config.yml
      service: microservices-base-config

  accounts:
    image: "ar2030/accounts:v2"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service: microservices-configserver-config

  loans:
    image: "ar2030/loans:v2"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"  #prefix always configserver and the hostname as the service name
      SPRING_PROFILES_ACTIVE: default
    extends:
      file: common-config.yml
      service: microservices-configserver-config

  cards:
    image: "ar2030/cards:v2"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071"  #prefix always configserver and the hostname as the service name
      SPRING_PROFILES_ACTIVE: default
    extends:
      file: common-config.yml
      service: microservices-configserver-config

networks:
  finbank:
    driver: bridge