server:
  port: 9010

spring:
  application:
    name: message  # must be the same as prefix of profiles in config repo
  cloud:
    function:
      definition: emailsms
    stream:
      bindings:
        emailsms-in-0:
          destination: send-communication  # queue name
          group:
        emailsms-out-0:
          destination: communication-sent  # queue name

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

management:
    metrics:
      tags:
        application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
